### ISSUE TITLE
Translucent white lines

### ISSUE THREAD

**Issue by kolaa** [PlayUAV/PlayuavOSD#11]
I see a translucent white lines across the width of the screen, where text is displayed.

Pal system; Pixim Seawolf camera

**Comment by ghost** [comment]
Thanks for your reporting. Could you please show a picture of the "translucent white line"? The PLAYUAV forum could be helpful:
http://en.playuav.com

**Comment by ghost** [comment]
The problem seemed to be caused by the improper setting of resistance. The current R12 value is 3K and R14 value 1.5K. The value of R12 and R14 should be the same, either 3K or 1.5k. After unifying the resistance, the white bars may still appear when power on but will disappear after a while. We also find that if we increase the value of C6 and C7 from 4.7uf to 10uf, the white bar issue won't be that obvious. 
See:http://en.playuav.com/question/5
