### ISSUE TITLE
ArmState overlap

### ISSUE THREAD

**Issue by N-Z-N** [PlayUAV/PlayuavOSD#21]
When unit is ARMED, leftover characters from DISARMED overlap ARMED text.
Tested on PixHawk v3.3 rc12.
https://www.youtube.com/watch?v=ULU41cqCsyo

**Comment by N-Z-N** [comment]
Looks like there is more overlap.
Both the ArmState and FlightMode fields do the same thing.
The old value does not get removed, or at least it alternates.

Armstate
When ARMED, the DISARMED value is still visible. It switches back and forth.

FlightMode 
Same thing, any state you change to will alternate with STAB.

**Comment by ghost** [comment]
I got the same issue with ArduPlan V3.3 in HITL. I didn't test ArduCopter 3.3 in a real flight. But I can sure this never happened with ArduCopter V3.2.1(I have flight my copter with V3.2.1  many times). 
We couldn't got if it is caused by the Ardupilot firmware. On the OSD side, it will clear the whole screen display before drawing. It means the OSD won't cause overlap. The only reason is the data(ArmState, FlightMode) from Ardupilot changing incessant.

**Comment by ghost** [comment]
This issue be fixed after updating the MAVLINK library. Tested with ArduCopter V3.3. 
Closed.

**Comment by ghost** [comment]
This issue still exist when connect the Flight Control like pixhawk to MissionPlaner through USB. The flickers disappears when USB disconnect from FC.

**Comment by N-Z-N** [comment]
Confirmed working fine now on 3.3 copter.

**Comment by ghost** [comment]
Yes. But when you connect the FC to the GCS, also the OSD connected. The flicker still happens. Randy(developer of Ardupilot) gave me some suggestions. Following his suggestion, this issue has been fixed. Will publish the new firmware.

**Comment by ghost** [comment]
Firmware Ver10 fixed. Closed.
